export const ACTION_TYPE = {
  INIT_CATEGORIES: "INIT_CATEGORIES",
  INIT_VIDEOS: "INIT_VIDEOS",
  CATEGORY: "CATEGORY",
  SORT_BY: "SORT_BY",
  SEARCH: "SEARCH",
  LOG_OUT: "LOG_OUT",
  ADD_TO_HISTORY: "ADD_TO_HISTORY",
  REMOVE_FROM_HISTORY: "REMOVE_FROM_HISTORY",
  CLEAR_HISTORY: "CLEAR_HISTORY",
};
